cam_info:
  -
    cam_id: 1
    cam_serial_num: "147322072736"
    type: realsense
  -
    cam_id: 2
    cam_serial_num: "028522071213"
    type: realsense

cam_config:
  realsense:
    width: 640
    height: 480
    fps: 30
    processing_preset: 1
    depth: True
  fisheye:
    width: 640
    height: 480
    fps: 30
